---
- name: Install build requirements
  apt: name={{ item }} state=present
  with_items:
    - libxml2-dev
    - libxslt1-dev

  # "force" uploads if the contents are different; default is only upload if dest doesn't exist.
- name: Upload requirements.txt
  copy: src=requirements.txt dest="{{ archiver_requirements_path }}" force=yes

- name: Install Python requirements
  pip: requirements="{{ archiver_requirements_path }}" virtualenv="{{ ckan_virtualenv_path }}"

- name: Install ckanext-archiver into ckan virtualenv
  pip:
    name: "git+http://github.com/okfn/ckanext-archiver.git@{{ ckanext_archiver_version }}#egg=ckanext-archiver"
    virtualenv: "{{ ckan_virtualenv_path }}"

- name: Clean up requirements.txt
  file: dest="{{ archiver_requirements_path }}" state=absent
