---
- name: Upload requirements.txt
  copy: src=requirements.txt dest="{{ qa_requirements_path }}"

- name: Install Python requirements
  pip: requirements="{{ qa_requirements_path }}" virtualenv="{{ ckan_virtualenv_path }}"

- name: Install ckanext-qa into ckan virtualenv
  pip:
    name: "git+https://github.com/ckan/ckanext-qa.git@{{ ckanext_qa_version }}#egg=ckanext_qa"
    virtualenv: "{{ ckan_virtualenv_path }}"

- name: Add self to CKAN plugin list
  lineinfile: dest="{{ ckan_config_path }}" regexp="^ckan.plugins(((?!qa).)*)$" line="ckan.plugins\1 qa" backrefs=yes

- name: Clean up requirements.txt
  file: dest="{{ qa_requirements_path }}" state=absent
