---
# Using the ansible pip module here results in breakage
- name: Install ckanext-issues into ckan virtualenv
  command: "{{ ckan_virtualenv_path }}/bin/pip install -e git+https://github.com/okfn/ckanext-issues.git@{{ ckanext_issues_version }}#egg=ckanext-issues"

- name: Add self to CKAN plugin list
  lineinfile: dest="{{ ckan_config_path }}" regexp="^ckan.plugins(((?!issues).)*)$" line="ckan.plugins\1 issues" backrefs=yes
  notify: Restart Apache

- name: Notify admins of new issues
  lineinfile: dest="{{ ckan_config_path }}" regexp="ckanext\.issues\.notify_admin" line="ckanext.issues.notify_admin = {{ ckanext_issues_notify_admin }}" insertafter="ckan\.plugins"
  notify: Restart Apache

- name: Notify owners of new issues
  lineinfile: dest="{{ ckan_config_path }}" regexp="ckanext\.issues\.notify_owner" line="ckanext.issues.notify_owner = {{ ckanext_issues_notify_owner }}" insertafter="ckan\.plugins"
  notify: Restart Apache

- name: Set from address for email notifications
  lineinfile: dest="{{ ckan_config_path }}" regexp="ckanext\.issues\.from_address" line="ckanext.issues.from_address = {{ ckanext_issues_from_address }}" insertafter="ckan\.plugins"
