---
# Using the ansible pip module here results in breakage
- name: Install datajson dependencies
  command: "{{ ckan_virtualenv_path }}/bin/pip install jsonschema pyyaml lepl"

- name: Install ckanext-datajson into ckan virtualenv
  command: "{{ ckan_virtualenv_path }}/bin/pip install -e git+https://github.com/azavea/ckanext-datajson.git@{{ ckanext_datajson_version }}#egg=ckanext-datajson"
  when: ckan_production

- name: Symlink ckanext-datajson into ckan virtualenv
  file: src={{ vagrant_ckanext_datajson_mountpoint }} dest={{ ckan_virtualenv_path }}/src/ckanext-datajson
        state=link
  when: not ckan_production

- name: Run setup.py develop
  command: "{{ ckan_virtualenv_path }}/bin/python setup.py develop
            chdir={{ ckan_virtualenv_path }}/src/ckanext-datajson"
  when: not ckan_production


- name: Add workaround to apache.wsgi
  lineinfile: dest={{ ckan_wsgi_path }}
              line="import ckanext"
              state=present
              insertbefore="^from paste\.deploy"

- name: Add self to CKAN plugin list
  lineinfile: dest="{{ ckan_config_path }}" regexp="^ckan.plugins(((?!datajson).)*)$" line="ckan.plugins\1 datajson" backrefs=yes
  notify: Restart Apache
