---
- name: Install Python dependencies
  pip: name="{{ item.name }}" version="{{ item.version }}" state=present
  with_items:
    - name: requests
      version: 2.4.3
    - name: ckanapi
      version: 3.3
    - name: python-slugify
      version: 0.1.0
