---
- hosts: vagrant
  sudo: True
  roles:
    - { role: "ckan" }
    - { role: "ckanext-archiver" }
    - { role: "ckanext-qa" }
    - { role: "odp-importer" }
    - { role: "ckan-odp-configuration" }
