---
- hosts: vagrant

  become: True

  pre_tasks:
    - name: Update APT cache
      apt: update_cache=yes

  roles:
    - { role: "azavea.postgresql" }
    - { role: "ckan" }
    - { role: "ckanext-disqus" }
    - { role: "ckanext-issues" }
    - { role: "ckanext-spatial" }
# deadoralive disabled until false positive issues are worked out
#    - { role: "ckanext-deadoralive" }
    - { role: "ckanext-datajson" }
#    - { role: "ckan-deadoralive" }
    - { role: "ckanext-odp_theme" }
    - { role: "ckanext-googleanalytics" }
    - { role: "ckan-odp-configuration" }
